### PR TITLE
Add support for raspbian

### PR DESCRIPTION
**Pull request by aidanharris**

### CODE REVIEW

**Comment by retrohacker** [comment]
Woah, this is rad @aidanharris :heart:

Would you mind adding a test case to validate the logic here: https://github.com/retrohacker/getos/blob/master/tests/mockdata.json

I don't have a pi handy to test this with.

**Comment by aidanharris** [comment]
@retrohacker The logic is the same as debian (hence the symlink) so I'm not sure a test case is needed beyond checking for the presence of the /etc/rpi-issue file which is not really a release file per say but does identify raspbian in the sense that this file should only be present on the raspbian os. Might it be a good idea to fallback to lsb_release if a release file is unavailable?

**Comment by aidanharris** [comment]
It doesn't look like its possible to mock the data because the debian logic calls lsb_release which will return different output depending on what machine its run on. I could probably use a docker image of some sort but don't think it would run in travis unless they support the ARM architecture?

**Comment by retrohacker** [comment]
Ah, so at closer look it appears this PR is using the `rpi-issue` file for detecting that this is in fact a raspberry pi. I'm not 100% opposed to this, but I'd rather rely on a release file that would allow us to parse version information if possible. Does the pi come with a `/etc/release` like file? If so, we should be able to use that with either an existing or custom parser to get the version information.

**Comment by aidanharris** [comment]
@retrohacker There's the /etc/os-release file which a lot of Linux distros use (so you can't use it to specifically identify Raspbian). A generic parser could try to read the values though and return the distribution or an educated guess. On the Pi it looks as follows:

```sh
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by retrohacker** [comment]
Sorry for the radio silence on this, your follow up comment must have gotten lost in my email :-\

https://github.com/retrohacker/getos/blob/master/logic/debian.js

This doesn't look like the correct logic for parsing the rpi-issue file:

```
Raspberry Pi reference 2017-04-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, acc4f56597e75225b93be3e1e20504a40565a9b9, stage2
```

It only works because `lsb_release` is installed. Taking a pass at parsing the file you posted now.

**Comment by retrohacker** [comment]
Landed in b1050037a41c6c6eef1aaa7e9141b1f3dcfe67be

`{ "codename": "jessie", "dist": "Raspbian", "os": "linux", "release": "8" }`

**Pull request closed without merging**
